![PY STAT.PNG]()

#DATA & ANALYTICS

----------------------------
PANDAS

Instructor: Ing. Yaneth Ccahuantico

E-mail: yane.data@gmail.com

www.datayanalytics.com

In [ ]:

print("Hola mundo")

Hola mundo

# DataFrame

In [ ]:
import pandas as pd # Librería para manejo de DataFrame
import random

In [ ]:
df1 = pd.DataFrame(
    data=np.random.randint(0, 21, (10, 4)) ,   # 6 filas y 4 columnas
    columns=["a", "b", "c", "d"]
    )
df1

    a   b   c   d
0  17  14  16   0
1   4   4  16  15
2  11  11   0   0
3   8  18   6  17
4   1   0  11   2
5  18   9   4  11
6   5  20  12   8
7  19   4  15  15
8  17  15  10  13
9   6   8   1   7

In [ ]:
import seaborn as sns # Librería para Visualización de datos

In [ ]:
# Data disponible
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
df3 = sns.load_dataset('iris')

In [ ]:
df3.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Data: Cargar data desde la Web

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
#Archivo en csv

df4 = pd.read_csv('/content/drive/MyDrive/Clases/Instructor. ESTADISTICA Con PYTHON + COLAB/Módulo 1/Data/autos.csv', sep=';')

In [ ]:
df4.head(6)

,Millas_Por_Galon,Cilindros,Pais_Origen,Peso_En_Libras,Desplazamiento,Aceleracion,Nombre,Anyo,Caballo_De_Fuerza
0,18.0,8,USA,3504,307.0,12.0,chevrolet chevelle malibu,1/01/1970,130.0
1,15.0,8,USA,3693,350.0,11.5,buick skylark 320,1/01/1970,165.0
2,18.0,8,USA,3436,318.0,11.0,plymouth satellite,1/01/1970,150.0
3,16.0,8,USA,3433,304.0,12.0,amc rebel sst,1/01/1970,150.0
4,17.0,8,USA,3449,302.0,10.5,ford torino,1/01/1970,140.0
5,15.0,8,USA,4341,429.0,10.0,ford galaxie 500,1/01/1970,198.0

In [ ]:
#Archivo en txt
df5 = pd.read_csv('/content/drive/MyDrive/Clases/Instructor. ESTADISTICA Con PYTHON + COLAB/Módulo 1/Data/autos.txt', sep='\t')

In [ ]:
df5.head()

,Millas_Por_Galon,Cilindros,Pais_Origen,Peso_En_Libras,Desplazamiento,Aceleracion,Nombre,Anyo,Caballo_De_Fuerza
0,18.0,8,USA,3504,307.0,12.0,chevrolet chevelle malibu,1/01/1970,130.0
1,15.0,8,USA,3693,350.0,11.5,buick skylark 320,1/01/1970,165.0
2,18.0,8,USA,3436,318.0,11.0,plymouth satellite,1/01/1970,150.0
3,16.0,8,USA,3433,304.0,12.0,amc rebel sst,1/01/1970,150.0
4,17.0,8,USA,3449,302.0,10.5,ford torino,1/01/1970,140.0

In [ ]:
#Archivo en Excel
df6 = pd.read_excel('/content/drive/MyDrive/Clases/Instructor. ESTADISTICA Con PYTHON + COLAB/Módulo 1/Data/autos.xlsx')

In [ ]:
df6.head()

,Millas_Por_Galon,Cilindros,Pais_Origen,Peso_En_Libras,Desplazamiento,Aceleracion,Nombre,Anyo,Caballo_De_Fuerza
0,18.0,8,USA,3504,307.0,12.0,chevrolet chevelle malibu,1970-01-01,130.0
1,15.0,8,USA,3693,350.0,11.5,buick skylark 320,1970-01-01,165.0
2,18.0,8,USA,3436,318.0,11.0,plymouth satellite,1970-01-01,150.0
3,16.0,8,USA,3433,304.0,12.0,amc rebel sst,1970-01-01,150.0
4,17.0,8,USA,3449,302.0,10.5,ford torino,1970-01-01,140.0

## Data: Cargar data desde la PC

In [ ]:
#cargamos la data desde nuestra PC
from google.colab import files
files.upload()

In [ ]:
df7 = pd.read_csv("datos_seguros.txt", sep="\t", header=0)

In [ ]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45798 entries, 0 to 45797
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   MES_T0                   45798 non-null  int64
 1   VENTA_SEGURO             45798 non-null  int64
 2   NUM_TC_TOTAL_T2          25397 non-null  float64
 3   SALDO_BCO_T2             25452 non-null  float64
 4   LINEA_BCO_T2             25452 non-null  float64
 5   USO_LINEA_BCO_T2         25452 non-null  float64
 6   Nro_CTa_Ahorro_Bco_T1    44405 non-null  float64
 7   Ahorro_Sldo_Bco_T1       44405 non-null  float64
 8   monto_ope_t2             32927 non-null  float64
 9   PROM_ANUAL_MTO_OPERA     32927 non-null  float64
 10  MAX_MTO_OPERA_Anual      32927 non-null  float64
 11  Ratio_HospvsMtoTotal_t2  29719 non-null  float64
 12  SEXO                     45798 non-null  object
 13  ANTIGUEDAD_MES           45798 non-null  int64
 14  DEPARTAMENTO             45798 non-null  object
 15  SOW_BCO_T2               45798 non-null  float64
 16  SOW_BCO_SEMESTRAL        45798 non-null  float64
dtypes: float64(12), int64(3), object(2)
memory usage: 5.9+ MB

In [ ]:
df7.head(10)

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
0,201506,0,3.0,0.0,2300.0,0.000000,0.0,0.0,15.00,18.644444,52.80,NaN,M,58,LIMA,0.000000,0.000000
1,201506,0,2.0,3215.0,3500.0,0.918571,0.0,0.0,548.98,2632.020000,5709.24,NaN,M,69,JUNIN,0.816134,0.930867
2,201506,0,1.0,3169.0,5000.0,0.633800,0.0,0.0,0.00,4999.000000,4999.00,0.0,M,16,CALLAO,1.000000,1.000000
3,201506,1,1.0,6495.0,8450.0,0.768639,2.0,505.0,2137.94,4900.191666,11206.80,NaN,F,62,LIMA,0.413831,0.505504
4,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,12.37,12.370000,12.37,NaN,F,5,AREQUIPA,0.000000,0.000000
5,201506,0,3.0,2373.0,9373.0,0.253174,0.0,0.0,411.86,1410.662727,5055.62,NaN,M,44,CALLAO,0.181633,0.677393
6,201506,0,2.0,0.0,0.0,0.000000,1.0,2662.0,46.00,218.393333,390.90,NaN,M,4,LIMA,0.000000,0.000000
7,201506,0,1.0,3023.0,16720.0,0.180801,0.0,0.0,2982.90,1721.769166,3137.70,0.0,M,136,LIMA,1.000000,1.000000
8,201506,0,1.0,1931.0,12500.0,0.154480,0.0,0.0,412.00,986.337500,2119.00,NaN,M,292,LIMA,0.278603,0.541839
9,201506,0,NaN,NaN,NaN,NaN,2.0,40718.0,1644.30,1581.335000,3565.14,NaN,F,49,AREQUIPA,0.000000,0.000000

Nombre de las columnas

In [ ]:
col = df7.columns
col

Index(['MES_T0', 'VENTA_SEGURO', 'NUM_TC_TOTAL_T2', 'SALDO_BCO_T2',
       'LINEA_BCO_T2', 'USO_LINEA_BCO_T2', 'Nro_CTa_Ahorro_Bco_T1',
       'Ahorro_Sldo_Bco_T1', 'monto_ope_t2', 'PROM_ANUAL_MTO_OPERA',
       'MAX_MTO_OPERA_Anual', 'Ratio_HospvsMtoTotal_t2', 'SEXO',
       'ANTIGUEDAD_MES', 'DEPARTAMENTO', 'SOW_BCO_T2', 'SOW_BCO_SEMESTRAL'],
      dtype='object')

Observamos la información de una variable

In [ ]:
df7['DEPARTAMENTO']

0               LIMA
1              JUNIN
2             CALLAO
3               LIMA
4           AREQUIPA
            ...
45793           LIMA
45794    LA LIBERTAD
45795           LIMA
45796          PIURA
45797          PASCO
Name: DEPARTAMENTO, Length: 45798, dtype: object

In [ ]:
df7.DEPARTAMENTO  # df6$Millas_Por_Galon

0               LIMA
1              JUNIN
2             CALLAO
3               LIMA
4           AREQUIPA
            ...
45793           LIMA
45794    LA LIBERTAD
45795           LIMA
45796          PIURA
45797          PASCO
Name: DEPARTAMENTO, Length: 45798, dtype: object

In [ ]:
# Información Fila
df7.loc[120]    # a nivel de Index

MES_T0                     201506
VENTA_SEGURO                    0
NUM_TC_TOTAL_T2               7.0
SALDO_BCO_T2                  0.0
LINEA_BCO_T2               5950.0
USO_LINEA_BCO_T2              0.0
Nro_CTa_Ahorro_Bco_T1         0.0
Ahorro_Sldo_Bco_T1            0.0
monto_ope_t2                  NaN
PROM_ANUAL_MTO_OPERA          NaN
MAX_MTO_OPERA_Anual           NaN
Ratio_HospvsMtoTotal_t2       0.0
SEXO                            F
ANTIGUEDAD_MES                158
DEPARTAMENTO                 LIMA
SOW_BCO_T2                    0.0
SOW_BCO_SEMESTRAL             0.0
Name: 120, dtype: object

In [ ]:
print("La cantidad de columnas en los datos es: ",df7.shape[1])
print("La cantidad de filas en los datos es: ",df7.shape[0])

La cantidad de columnas en los datos es:  17
La cantidad de filas en los datos es:  45798

In [ ]:
df7.describe().T.round(2)

,count,mean,std,min,25%,50%,75%,max
MES_T0,45798.0,201505.51,0.50,201505.0,201505.00,201506.00,201506.00,201506.00
VENTA_SEGURO,45798.0,0.02,0.15,0.0,0.00,0.00,0.00,1.00
NUM_TC_TOTAL_T2,25397.0,2.53,1.45,0.0,1.00,2.00,3.00,10.00
SALDO_BCO_T2,25452.0,1513.13,5265.76,0.0,0.00,0.00,78.00,96240.00
LINEA_BCO_T2,25452.0,7184.22,12511.11,0.0,0.00,2000.00,9600.00,178750.00
USO_LINEA_BCO_T2,25452.0,0.12,0.26,0.0,0.00,0.00,0.01,1.73
Nro_CTa_Ahorro_Bco_T1,44405.0,0.86,1.29,0.0,0.00,0.00,1.00,16.00
Ahorro_Sldo_Bco_T1,44405.0,2086.32,9416.85,0.0,0.00,0.00,782.00,778106.00
monto_ope_t2,32927.0,1694.08,6945.05,0.0,0.00,210.50,1148.78,275997.00
PROM_ANUAL_MTO_OPERA,32927.0,2088.76,6190.32,0.0,273.33,699.33,1783.70,216309.00
MAX_MTO_OPERA_Anual,32927.0,4745.68,12132.38,0.0,526.95,1512.81,4210.54,344970.00
Ratio_HospvsMtoTotal_t2,29719.0,0.02,0.11,0.0,0.00,0.00,0.00,1.00
ANTIGUEDAD_MES,45798.0,89.02,76.54,1.0,24.00,62.00,154.00,420.00
SOW_BCO_T2,45798.0,0.14,0.31,0.0,0.00,0.00,0.00,1.00
SOW_BCO_SEMESTRAL,45798.0,0.18,0.41,0.0,0.00,0.00,0.02,6.00

In [ ]:
df7[["MES_T0", "VENTA_SEGURO", "NUM_TC_TOTAL_T2"]].sample(7)

       MES_T0  VENTA_SEGURO  NUM_TC_TOTAL_T2
34801  201505             0              NaN
1916   201506             0              NaN
43582  201505             0              3.0
26656  201505             0              2.0
9313   201505             0              2.0
15306  201505             0              2.0
27897  201506             0              2.0

In [ ]:
# Datos duplicados

df7[df7["MES_T0"].duplicated()].head()

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
1,201506,0,2.0,3215.0,3500.0,0.918571,0.0,0.0,548.98,2632.020000,5709.24,NaN,M,69,JUNIN,0.816134,0.930867
2,201506,0,1.0,3169.0,5000.0,0.633800,0.0,0.0,0.00,4999.000000,4999.00,0.0,M,16,CALLAO,1.000000,1.000000
3,201506,1,1.0,6495.0,8450.0,0.768639,2.0,505.0,2137.94,4900.191666,11206.80,NaN,F,62,LIMA,0.413831,0.505504
4,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,12.37,12.370000,12.37,NaN,F,5,AREQUIPA,0.000000,0.000000
5,201506,0,3.0,2373.0,9373.0,0.253174,0.0,0.0,411.86,1410.662727,5055.62,NaN,M,44,CALLAO,0.181633,0.677393

In [ ]:
# revisando datos perdidos
df7.isna().sum()

MES_T0                         0
VENTA_SEGURO                   0
NUM_TC_TOTAL_T2            20401
SALDO_BCO_T2               20346
LINEA_BCO_T2               20346
USO_LINEA_BCO_T2           20346
Nro_CTa_Ahorro_Bco_T1       1393
Ahorro_Sldo_Bco_T1          1393
monto_ope_t2               12871
PROM_ANUAL_MTO_OPERA       12871
MAX_MTO_OPERA_Anual        12871
Ratio_HospvsMtoTotal_t2    16079
SEXO                           0
ANTIGUEDAD_MES                 0
DEPARTAMENTO                   0
SOW_BCO_T2                     0
SOW_BCO_SEMESTRAL              0
dtype: int64

In [ ]:
df7["DEPARTAMENTO"].unique()  # alternativas de nuestra variable

array(['LIMA', 'JUNIN', 'CALLAO', 'AREQUIPA', 'AYACUCHO', 'CUSCO',
       'LA LIBERTAD', 'LAMBAYEQUE', 'TACNA', 'PASCO', 'UCAYALI',
       'HUANUCO', 'ICA', 'PUNO', 'PIURA', 'ANCASH', 'SAN MARTIN',
       'CAJAMARCA', 'LORETO', 'TUMBES', 'APURIMAC', 'AMAZONAS',
       'MOQUEGUA', 'MADRE DE DIOS', 'HUANCAVELICA'], dtype=object)

In [ ]:
df7["GENERO"] = df7["SEXO"].apply(lambda x: "Masculino" if x=="M" else "Femenino")
df7[["SEXO", "GENERO"]].head()

  SEXO     GENERO
0    M  Masculino
1    M  Masculino
2    M  Masculino
3    F   Femenino
4    F   Femenino

In [ ]:
# ordenado de data por variables
df7.sort_values(["NUM_TC_TOTAL_T2", "SALDO_BCO_T2"], ascending=[False,True], inplace=True)
df7.head(10)

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL,GENERO
15281,201505,0,10.0,0.0,23000.0,0.000000,0.0,0.0,0.00,21899.500000,29792.00,0.0,M,134,LIMA,0.000000,0.238861,Masculino
36529,201506,0,10.0,11259.0,118163.0,0.095283,0.0,0.0,227.07,107.046666,261.23,NaN,M,164,LIMA,0.088293,0.096348,Masculino
22026,201506,0,9.0,0.0,70000.0,0.000000,0.0,0.0,0.00,46.450000,87.00,0.0,M,45,LIMA,0.000000,0.000000,Masculino
9042,201505,0,9.0,4027.0,18150.0,0.221873,0.0,0.0,3489.01,709.428333,3489.01,NaN,M,148,LIMA,0.330405,0.129106,Masculino
44939,201506,0,9.0,15091.0,27800.0,0.542841,2.0,412.0,46449.69,66817.442500,164858.00,NaN,M,48,LIMA,0.190278,0.116390,Masculino
3418,201505,0,8.0,0.0,17000.0,0.000000,0.0,0.0,3490.82,2712.333333,5134.84,0.0,M,30,LIMA,0.000000,0.000000,Masculino
4727,201505,0,8.0,0.0,5150.0,0.000000,0.0,0.0,0.00,698.267500,1354.98,0.0,F,211,LIMA,0.000000,0.017528,Femenino
5438,201505,0,8.0,0.0,41500.0,0.000000,1.0,0.0,NaN,NaN,NaN,0.0,M,231,LA LIBERTAD,0.000000,0.000000,Masculino
7556,201505,0,8.0,0.0,36000.0,0.000000,0.0,0.0,0.00,225.600000,750.50,0.0,M,137,LIMA,0.000000,0.000000,Masculino
12212,201505,0,8.0,0.0,16000.0,0.000000,3.0,0.0,0.00,180.000000,180.00,0.0,M,178,LA LIBERTAD,0.000000,0.000000,Masculino

In [ ]:
# tabla resumen 
df7.groupby(["VENTA_SEGURO", "GENERO"])["MES_T0"].count().reset_index()

   VENTA_SEGURO     GENERO  MES_T0
0             0   Femenino   17582
1             0  Masculino   27190
2             1   Femenino     241
3             1  Masculino     785

In [ ]:
# Operaciones matemáticas
df7["LINEA_BCO_DISPONIBLE"] = df7["LINEA_BCO_T2"] - df7["USO_LINEA_BCO_T2"]*df7["LINEA_BCO_T2"]
df7[["LINEA_BCO_T2", "USO_LINEA_BCO_T2", "LINEA_BCO_DISPONIBLE"]].head().round(2)

       LINEA_BCO_T2  USO_LINEA_BCO_T2  LINEA_BCO_DISPONIBLE
15281       23000.0              0.00              23000.00
36529      118163.0              0.10             106904.07
22026       70000.0              0.00              70000.00
9042        18150.0              0.22              14123.01
44939       27800.0              0.54              12709.02

# Instalar librerias en Python

In [ ]:
#instalar libreria

!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (1.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.21.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.1.0)

In [ ]:
#actualizar libreria a la última versión

!pip install --upgrade scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (1.0.2)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.21.6)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (3.1.0)

In [ ]:
#actualizar libreria a una versión específica

!pip install seaborn==0.11.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting seaborn==0.11.0
  Downloading seaborn-0.11.0-py3-none-any.whl (283 kB)
     |████████████████████████████████| 283 kB 5.1 MB/s
Requirement already satisfied: matplotlib>=2.2 in /usr/local/lib/python3.7/dist-packages (from seaborn==0.11.0) (3.2.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from seaborn==0.11.0) (1.21.6)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.7/dist-packages (from seaborn==0.11.0) (1.4.1)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from seaborn==0.11.0) (1.3.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn==0.11.0) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn==0.11.0) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn==0.11.0) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn==0.11.0) (0.11.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=2.2->seaborn==0.11.0) (4.2.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->seaborn==0.11.0) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=2.2->seaborn==0.11.0) (1.15.0)
Installing collected packages: seaborn
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.11.2
    Uninstalling seaborn-0.11.2:
      Successfully uninstalled seaborn-0.11.2
Successfully installed seaborn-0.11.0

In [ ]:
pd.__version__

'1.3.5'

In [ ]:
import pandas as pd

Gracias DATA & ANALYTICS!!!

www.datayanalytics.com